"""Generated documentation of the project-file format (``docs/formats/project-file.md``)."""

from __future__ import annotations

import json

from envelopelab.project.model import (
    PROJECT_FORMAT,
    PROJECT_FORMAT_VERSION,
    PROJECT_SUFFIX,
    Project,
)
from envelopelab.project.recovery import AUTOSAVE_FORMAT, AUTOSAVE_SUFFIX

KEYS: tuple[tuple[str, str], ...] = (
    ("`state.design`", "The design document (SI units: m, K, Pa, kg)."),
    (
        "`state.patterns.rows.<letter>`",
        "Pattern annotations of one panel row: printed label, grain angle (degrees from the "
        "panel x axis), fabric zone, seam-allowance override (m), notches, tape paths and "
        "feature locations (panel coordinates, m), and an optional **manual outline "
        "override** (m) with the time, reason and the geometry hash it was drawn over.",
    ),
    (
        "`locks`",
        "Constraint locks of the gore editor (height m, volume m³, maximum diameter m, gore "
        "count).",
    ),
    (
        "`state.shapes`",
        "Special shapes placed on the envelope (version 2): `kind` (`dome`, `tube`, "
        "`revolved` or `mesh`), unique `name`, `placement` (gore from 1, tape position m, "
        "fraction across the gore, lean and lean direction in degrees), the shape's sizes "
        "(m) or revolved profile (m) or mesh vertices (m) and triangles, panel or gore "
        "count, match marks per piece, feed-hole radius (m, optional), seam allowance (m) "
        "and skin fabric id (optional). Version 1 files read as having no shapes.",
    ),
    ("`snapshots`", "Named copies of `state` with their design content hash."),
    ("`versions`", "Committed design versions (`version_id`, `parent_id`, message, state)."),
    ("`provenance`", "Append-only log of flagged edits (manual overrides and their undo)."),
    (
        "`runs`",
        "Run records: solver (`envelopelab-preview` or `calculix`), status, convergence, "
        "final residual and what it measures, iterations, run time, mesh size, material "
        "sources, load case, design content hash, the **input fingerprint** that decides "
        "whether the run is still current, summary values and the run manifest.",
    ),
)


def render_project_docs() -> str:
    """Text of ``docs/formats/project-file.md`` (the project-file format page)."""
    schema = json.dumps(Project.model_json_schema(), indent=2, sort_keys=True)
    table = "\n".join(f"| {key} | {text} |" for key, text in KEYS)
    return f"""# Project file

_This page is generated by `scripts/generate_project_schema_docs.py` from
`envelopelab.project.model.Project`; do not edit it by hand._

An EnvelopeLab project (`*{PROJECT_SUFFIX}`) is a UTF-8 JSON file with
`"format": "{PROJECT_FORMAT}"` and `"format_version": {PROJECT_FORMAT_VERSION}`. It wraps one
design document, unchanged and in the [design schema](design-schema.md) (its
`meta.content_hash` is checked on load), with everything the desktop application edits
around it:

| Key | Content |
|---|---|
{table}

Result arrays of each run (positions, initial positions and triangles in m, principal
resultants in N/m, wrinkle state) are stored next to the project in
`<name>{PROJECT_SUFFIX}.runs/<run_id>.npz` (NumPy archive, no pickled objects);
`runs[].result_file` gives the relative path.

Files are written atomically (a temporary file is renamed over the target). While a
project has unsaved changes the application also writes autosave files
(`"format": "{AUTOSAVE_FORMAT}"`, `*{AUTOSAVE_SUFFIX}`: the project data plus the path of
the project file it belongs to) to a recovery folder; they are removed on save and on a
clean exit, and offered for recovery at the next start otherwise.

## Schema

```json
{schema}
```
"""
