"""Build the Alien reference mesh (test data) from the pack's 3D concept page.

``pack/alien-balloon-3d.html`` draws the concept with three.js: a lathe of the meridian
profile ``D.lat`` (radius, height in m) with the two eye regions (``D.eyeL``,
``D.eyeR``, polygons in the lathe's u-v texture space) pushed out radially by
``1.3 * min(1, d / 0.05) ** 0.8`` m, ``d`` being the distance to the eye outline in
stretched u-v units. This script repeats that construction, closes the mouth and crown
with flat caps, converts three.js y-up to z-up and writes ``reference/alien-reference.obj``
(m). It is test-fixture tooling: nothing in ``src/`` depends on it.

Run from the repository root::

    python tests/fixtures/alien/make_reference_mesh.py
"""

from __future__ import annotations

import json
import math
import re
from pathlib import Path
from typing import Any

import numpy as np

HERE = Path(__file__).resolve().parent
PAGE = HERE / "pack" / "alien-balloon-3d.html"
OUT = HERE / "reference" / "alien-reference.obj"
SEGMENTS = 120


def _data() -> dict[str, Any]:
    text = PAGE.read_text(encoding="utf-8")
    match = re.search(r"const D=(\{.*?\});\s*\n", text, re.S)
    if match is None:
        raise SystemExit("no scene data in the concept page")
    data: dict[str, Any] = json.loads(match.group(1))
    return data


def _inside(u: float, v: float, poly: np.ndarray) -> bool:
    inside = False
    j = len(poly) - 1
    for i in range(len(poly)):
        xi, yi = poly[i]
        xj, yj = poly[j]
        if (yi > v) != (yj > v) and u < (xj - xi) * (v - yi) / (yj - yi) + xi:
            inside = not inside
        j = i
    return inside


def main() -> None:
    d = _data()
    lat = np.array(d["lat"], dtype=float)
    idx = np.arange(len(lat))
    # The lathe's v coordinate is the point index fraction of the full profile.
    prof, v_of = lat[idx], idx / (len(lat) - 1)
    eyes = [np.array(d["eyeL"]), np.array(d["eyeR"])]
    rows: list[tuple[float, float, float]] = []
    for (r, y), v in zip(prof, v_of, strict=True):
        for i in range(SEGMENTS):
            u = i / SEGMENTS
            phi = u * 2.0 * math.pi
            bump = 0.0
            if 0.30 <= v <= 0.80:
                for k, poly in enumerate(eyes):
                    if (k == 0 and 0.28 < u < 0.5 or k == 1 and 0.5 <= u < 0.72) and _inside(
                        u, v, poly
                    ):
                        dist = np.sqrt(((u - poly[:, 0]) * 2.5) ** 2 + (v - poly[:, 1]) ** 2).min()
                        bump = 1.3 * min(1.0, dist / 0.05) ** 0.8
            rr = r + bump
            x3, y3, z3 = rr * math.sin(phi), y, rr * math.cos(phi)
            rows.append((x3, -z3, y3))  # y-up to z-up (a rotation, keeps handedness)
    verts = np.array(rows)
    tri: list[tuple[int, int, int]] = []
    n = SEGMENTS
    for j in range(len(prof) - 1):
        for i in range(n):
            a, b = j * n + i, j * n + (i + 1) % n
            c, e = (j + 1) * n + i, (j + 1) * n + (i + 1) % n
            tri += [(a, e, b), (a, c, e)]
    bottom = len(verts)
    top = bottom + 1
    verts = np.vstack([verts, [0.0, 0.0, prof[0, 1]], [0.0, 0.0, prof[-1, 1]]])
    last = (len(prof) - 1) * n
    for i in range(n):
        tri.append((bottom, i, (i + 1) % n))
        tri.append((top, last + (i + 1) % n, last + i))
    faces = np.array(tri)
    # Orient outward (positive divergence volume).
    e = verts[faces]
    if np.einsum("mi,mi->m", e[:, 0], np.cross(e[:, 1], e[:, 2])).sum() < 0:
        faces = faces[:, [0, 2, 1]]
    lines = [
        "# Alien reference mesh (test data) generated by make_reference_mesh.py from",
        "# pack/alien-balloon-3d.html; units m, z up.",
    ]
    lines += [f"v {x:.5f} {y:.5f} {z:.5f}" for x, y, z in verts]
    lines += [f"f {a + 1} {b + 1} {c + 1}" for a, b, c in faces]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    e = verts[faces]
    vol = abs(np.einsum("mi,mi->m", e[:, 0], np.cross(e[:, 1], e[:, 2])).sum()) / 6
    print(f"{OUT}: {len(verts)} vertices, {len(faces)} triangles, volume {vol:.0f} m^3")


if __name__ == "__main__":
    main()
