"""Regression tests: generic standard-gore and special-shape fixtures, and the Alien pack.

The generic fixtures (tests/fixtures/standard_gore, tests/fixtures/special_shape) are
synthetic designs generated by tests/fixtures/generate_generic_fixtures.py. The Alien
build pack (tests/fixtures/alien) is a regression fixture only: it must import, audit and
assemble with no source-code special cases.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np
import pytest

from envelopelab.assembly.pipeline import BuildPackResult, import_build_pack
from envelopelab.assembly.reports import write_reports
from envelopelab.assembly.rest_model import load_rest_model, save_rest_model
from envelopelab.geometry.polygon import distance_to_polyline
from envelopelab.validation.pattern_import import (
    fixture_paths,
    render_markdown,
    run_fixtures,
)

ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "tests" / "fixtures"
GOLDEN = Path(__file__).resolve().parent / "golden" / "alien-import-summary.json"
PAGE = ROOT / "docs" / "validation" / "pattern-import-fixtures.md"


@pytest.fixture(scope="module")
def standard() -> BuildPackResult:
    return import_build_pack(FIXTURES / "standard_gore" / "build-pack.yaml")


@pytest.fixture(scope="module")
def special() -> BuildPackResult:
    return import_build_pack(FIXTURES / "special_shape" / "build-pack.yaml")


@pytest.fixture(scope="module")
def alien() -> BuildPackResult:
    return import_build_pack(FIXTURES / "alien" / "build-pack.yaml")


def test_standard_gore_has_exactly_mouth_and_crown_loops(standard: BuildPackResult) -> None:
    report = standard.mesh_report
    assert report is not None
    assert sorted(loop.opening or "?" for loop in report.boundary_loops) == ["crown", "mouth"]
    assert report.passed, report.checks
    assert report.components == 1
    assert report.edges_nonmanifold == 0
    assert report.euler_characteristic == 0  # a sphere with two holes
    assert abs(report.area_relative_error) <= 0.005
    loops = {loop.opening: loop.rest_length for loop in report.boundary_loops}
    ring = standard.spec.rings[0]
    bottom = standard.pieces[ring.rows[0]]
    assert loops["mouth"] == pytest.approx(
        ring.gore_count * standard.assembly.instances["body/A@1"].edges["bottom"].length, rel=1e-9
    )
    assert bottom.valid


def test_standard_gore_audit_is_clean(standard: BuildPackResult) -> None:
    assert standard.audit.error_count == 0
    assert max(r.abs_mismatch for r in standard.audit.rows) < 1e-4
    assert standard.status == "PASS"


def test_cut_only_import_matches_sew_lines(standard: BuildPackResult) -> None:
    cut_only = import_build_pack(FIXTURES / "standard_gore" / "build-pack-cut-only.yaml")
    for pid, piece in standard.pieces.items():
        other = cut_only.pieces[pid]
        assert other.outline_source == "inset"
        assert np.max(distance_to_polyline(piece.outline, other.outline, True)) < 5e-4
        assert other.finished_area == pytest.approx(piece.finished_area, rel=1e-4)
    assert cut_only.mesh_report is not None and cut_only.mesh_report.passed


def test_special_shape_appendage_seam_with_designed_ease(special: BuildPackResult) -> None:
    graph = special.assembly.graph
    base = next(s for s in graph.seams if s.seam_id == "tube_base")
    assert base.seam_type == "appendage"
    assert base.props.designed_ease_m == pytest.approx(0.040)
    row = next(r for r in special.audit.rows if r.seam_id == "tube_base")
    assert row.severity == "info"
    assert row.length_b - row.length_a == pytest.approx(0.040, abs=2e-4)
    assert row.abs_mismatch < 1e-3
    assert special.audit.error_count == 0


def test_special_shape_mesh_is_closed_except_mouth_and_crown(special: BuildPackResult) -> None:
    report = special.mesh_report
    assert report is not None
    assert report.passed, report.checks
    assert sorted(loop.opening or "?" for loop in report.boundary_loops) == ["crown", "mouth"]
    assert report.components == 1
    assert report.orientation_conflicts == 0
    assert abs(report.area_relative_error) <= 0.005


def test_special_shape_rest_model_carries_ease_and_tags(
    special: BuildPackResult, tmp_path: Path
) -> None:
    assert special.rest_model is not None
    path = save_rest_model(special.rest_model, tmp_path / "rest.json")
    data = load_rest_model(path)
    seams = {s["id"]: s for s in data["seams"]}
    assert seams["tube_base"]["designed_ease_m"] == pytest.approx(0.040)
    assert seams["tube_base"]["type"] == "appendage"
    assert seams["body:v:1/2:A"]["load_tape"] == "25 mm load tape"
    assert any(k.endswith(":tape0") for k in data["tape_paths"])
    zones = {i["id"]: i["material_zone"] for i in data["instances"]}
    assert zones["tube"] == "appendage"
    grains = {i["id"]: i["grain"] for i in data["instances"]}
    assert grains["body/B@1"] == pytest.approx([1.0, 0.0])
    assert "not an inflated or solved shape" in data["status"]
    assert data["metadata"]["design_content_hash"] == special.imported.content_hash
    positions = np.array(data["nodes"]["initial_positions"])
    assert positions.shape == (special.rest_model.mesh.n_nodes, 3)
    assert np.all(np.isfinite(positions))


def test_reports_are_written(special: BuildPackResult, tmp_path: Path) -> None:
    files = write_reports(special, tmp_path)
    expected = {
        "panel-inventory.csv",
        "panel-inventory.json",
        "panel-inventory.html",
        "seam-audit.csv",
        "seam-audit.json",
        "seam-audit.html",
        "seam-graph.csv",
        "seam-graph.json",
        "mesh-report.json",
        "mesh-report.html",
        "import-warnings.json",
        "import-warnings.csv",
        "import-warnings.html",
        "rest-model.json",
        "index.html",
    }
    assert {p.name for p in files.values()} == expected
    inventory = json.loads((tmp_path / "panel-inventory.json").read_text(encoding="utf-8"))
    tube = next(r for r in inventory if r["piece_id"] == "TUBE")
    assert tube["assembled"] == 1 and tube["kind"] == "appendage"
    assert tube["finished_area_m2"] < tube["cut_area_m2"]
    assert "Status: PASS" in (tmp_path / "index.html").read_text(encoding="utf-8")


@pytest.mark.slow
def test_alien_imports_and_assembles(alien: BuildPackResult, tmp_path: Path) -> None:
    report = alien.mesh_report
    assert report is not None
    assert report.passed, report.checks
    assert report.unintended_holes == 0
    assert report.components == 1
    assert report.edges_nonmanifold == 0
    assert report.edges_attachment > 0  # antenna cones sewn onto marked base lines
    assert abs(report.area_relative_error) <= 0.005
    assert alien.audit.error_count == 0
    assert not [w for w in alien.warnings if w.severity == "error"]
    files = write_reports(alien, tmp_path)
    assert files["rest_model"].exists()


@pytest.mark.slow
def test_alien_matches_golden_summary(alien: BuildPackResult) -> None:
    golden = json.loads(GOLDEN.read_text(encoding="utf-8"))
    pieces = {pid: p for pid, p in alien.pieces.items()}
    assert sorted(pieces) == sorted(golden["pieces"])
    for pid, expected in golden["pieces"].items():
        piece = pieces[pid]
        assert piece.quantity == expected["quantity"], pid
        assert piece.finished_area == pytest.approx(expected["finished_area_m2"], abs=1e-6), pid
        assert piece.cut_area == pytest.approx(expected["cut_area_m2"], abs=1e-6), pid
    assert len(alien.audit.rows) == golden["seams"]
    assert alien.mesh_report is not None
    openings = sorted(loop.opening or "?" for loop in alien.mesh_report.boundary_loops)
    assert openings == golden["openings"]
    eye = next(r for r in alien.audit.rows if r.seam_id == "eye_rim_left")
    assert eye.severity == "info"
    assert eye.designed_ease == pytest.approx(1.240)


def test_no_design_specific_code() -> None:
    """The library must not special-case any fixture (AGENTS.md hard rule).

    ``validation/pattern_import.py`` is exempt: it lists the fixture files and writes the
    validation page text about them; it contains no engineering logic.
    """
    # Material names such as Nomex are library data, not design special cases.
    pattern = re.compile(r"alien|antenna|eye[_ ]?pod", re.IGNORECASE)
    exempt = ROOT / "src" / "envelopelab" / "validation" / "pattern_import.py"
    offenders = [
        str(path.relative_to(ROOT))
        for path in (ROOT / "src").rglob("*.py")
        if path != exempt and pattern.search(path.read_text(encoding="utf-8"))
    ]
    assert not offenders


@pytest.mark.slow
def test_generated_page_is_current() -> None:
    summaries = run_fixtures(fixture_paths(ROOT))
    assert all(s.passed for s in summaries), [s.name for s in summaries if not s.passed]
    assert PAGE.read_text(encoding="utf-8") == render_markdown(summaries), (
        "docs/validation/pattern-import-fixtures.md is stale; "
        "run python scripts/generate_validation_docs.py"
    )
