"""Smoke solve of the generic spherical envelope fixture, from DXF patterns to equilibrium.

The fixture (tests/fixtures/spherical_envelope) is a synthetic 12-gore sphere generated by
tests/fixtures/generate_generic_fixtures.py. The solve uses generic assumed materials.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from envelopelab.solvers.dynamic_relaxation import SolveResult, solve
from envelopelab.solvers.membrane import TAUT
from envelopelab.solvers.model import SolverModel
from envelopelab.solvers.results import factors_of_safety, force_balance
from envelopelab.validation.preview_solver import SMOKE_LEVEL_MM, envelope_model

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"
SPHERE = FIXTURES / "spherical_envelope" / "build-pack.yaml"


@pytest.fixture(scope="module")
def smoke() -> tuple[SolverModel, SolveResult]:
    model = envelope_model(SPHERE, SMOKE_LEVEL_MM)
    return model, solve(model)


@pytest.mark.slow
def test_smoke_solve_converges_and_balances(smoke: tuple[SolverModel, SolveResult]) -> None:
    model, result = smoke
    assert isinstance(result, SolveResult)
    assert result.converged, result.convergence
    assert not result.errors
    balance = force_balance(result)
    assert balance.passed, balance
    # Pressure resultant equals the lift of the enclosed volume (mouth at zero pressure).
    pressure = result.loads.pressure[2] + result.loads.closures["crown"][2]
    assert pressure == pytest.approx(result.lift, rel=5e-3)
    # A 7 m sphere cut between -72 and +78 deg latitude holds about 1 350 m^3.
    assert 1250.0 < result.volume < 1450.0


@pytest.mark.slow
def test_smoke_solve_finds_wrinkles_low_and_tension_high(
    smoke: tuple[SolverModel, SolveResult],
) -> None:
    model, result = smoke
    centroid_z = result.positions[model.triangles].mean(axis=1)[:, 2]
    taut = result.state == TAUT
    assert 0 < taut.sum() < model.n_triangles
    assert centroid_z[~taut].mean() < centroid_z[taut].mean()
    assert any(w.code == "wrinkles" for w in result.warnings)
    # Where the fabric wrinkles (lower rows A, B) the vertical tapes carry the meridional
    # load; the crown ring tape carries the parachute (closure) load as hoop tension.
    lower = [c.name for c in model.cables if ":v:" in c.name and c.name[-1] in "AB"]
    assert lower and all(result.tape_tensions[n].min() > 0.0 for n in lower)
    assert result.tape_tensions["body:rim:crown"].min() > 0.0


@pytest.mark.slow
def test_smoke_solve_reports_safety_factors_with_sources(
    smoke: tuple[SolverModel, SolveResult],
) -> None:
    model, result = smoke
    rows = factors_of_safety(model, result)
    kinds = {r.kind for r in rows}
    assert kinds == {"zone", "seam", "tape"}
    assert all(r.source == "assumed" for r in rows)
    assert all(r.passed for r in rows), [r for r in rows if not r.passed]
    assert result.metadata["design_content_hash"] == model.source_hash != ""
